<!--Form Tittle-->
<div class="page-title">
    <h2>Form Edit Product's Price</h2>
</div>
<!--Form Information-->
<form id="product-form-validate">
    <div class="fieldset">
        <h2 class="legend">Product Information</h2>
        <ul class="form-list" style="list-style-type:none">
            <li class="fields">
                <div class="field product">
                    <label class="required" for="product">Product Id</label>
                    <div class="input-box">
                        <select name="id" id="id">
                            <?php
                            $collection = $block->getProductCollection();
                            foreach($collection as $product):?>

                                <option value=<?=$product->getId(); ?>> <?=$product->getId(); ?> </option>

                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field price">
                    <label class="required" for="price">New Price</label>
                    <div class="input-box">
                        <input type="number" class="input-text required-entry" maxlength="25" title="Price" value="" name="final_price" id="final_price" size="30">
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field status">
                    <label class="required" for="status">Status</label>
                    <div class="input-box">
                        <select name="status" id="status">
                            <option value="1">Available</option>
                            <option value="0">Unavailable</option>
                        </select>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</form>
<button class="button" title="Update" id="update" type="reset"><span>Update</span></button>

<div class="content">
    <p id="change">Change to List Product -> -> -></p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#update").click(function () {
            var id = $('#id').val();
            var price = $('#final_price').val();
            var status = $('#status').val();

            // Ít nhất price cũng phải có giá trị điền vào thì nó mới alert được
            $.ajax({
                // Gửi request đến url của Controller Addproduct.php để lưu dữ liệu
                url: "<?php echo $block->getUrl('hellomagento/addproduct/addproduct'); ?>",
                data: {id: id, price: price, status: status},
                success: function(result) {
                    $("#change").html(result);
                }
            });
        });
    });

</script>