<!--Form Tittle-->
<div class="page-title">
    <h2>Form Edit Product's Price</h2>
</div>
<!--Form Information-->
<form id="product-form-validate" method="post" action="<?php echo $block->getActionOfForm()?>">
    <div class="fieldset">
        <h2 class="legend">Product Information</h2>
        <ul class="form-list" style="list-style-type:none">
            <li class="fields">
                <div class="field product">
                    <label class="required" for="product">Product Id</label>
                    <div class="input-box">
                        <select name="product" id="product">
                            <?php
                            $collection = $block->getProductCollection();
                            foreach($collection as $product):?>

                                <option value=<?=$product->getId(); ?>> <?=$product->getId(); ?> </option>

                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field price">
                    <label class="required" for="price">New Price</label>
                    <div class="input-box">
                        <input type="number" class="input-text required-entry" maxlength="25" title="Price" value="" name="price" id="price" size="30">
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field status">
                    <label class="required" for="status">Status</label>
                    <div class="input-box">
                        <select name="status" id="status">
                            <option value="1">Available</option>
                            <option value="0">Unavailable</option>
                        </select>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!--Button-->
    <div class="buttons-set">
        <button class="button" title="Add" type="submit"><span><span>Update</span></span></button>
    </div>
</form>