<h1> This is templates for Block </h1>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

<table>
    <tr>
        <th>STT</th>
        <th>Product Name</th>
        <th>Product SKU</th>
        <th>Price</th>
        <th>Action</th>
    </tr>

    <?php
    $collection = $block->getProductCollection();
//    $collection->addAttributeToFilter('price', array('eq' => 0));
//    $collection->addFieldToFilter(array(array('attribute'=>'price', 'neq'=>"0" )));
    foreach($collection as $product):?>
        <tr>
            <td> <?=$product->getId(); ?> </td>
            <td> <?=$product->getName(); ?> </td>
            <td> <?=$product->getSKU(); ?> </td>
            <td> <?php echo "$" . number_format($product->getPrice(), 2, ".", ","); ?> </td>
            <td> <p><a href= <?php echo $product->getProductUrl(); ?> > View Detail </a></p> </td>
        </tr>
    <?php endforeach;?>
</table>
